// app-general
export const SHOW_PAGE_LOADER = "SHOW_PAGE_LOADER/app";
export const HIDE_PAGE_LOADER = "HIDE_PAGE_LOADER/app";
export const SHOW_ALERT = "SHOW_ALERT/app";
export const HIDE_ALERT = "HIDE_ALERT/app";
export const RESET_VALUES_ALERT = "RESET_VALUES_ALERT/app";
// home
export const SET_STOCKS_HOME = "SET_STOCKS/home";
export const SHOW_PAGINATION_STOCKS_LOADER_HOME = "SHOW_PAGINATION_STOCKS_LOADER_HOME/home";
export const HIDE_PAGINATION_STOCKS_LOADER_HOME = "HIDE_PAGINATION_STOCKS_LOADER_HOME/home";
export const SET_PAGE_NUMBER_STOCKS_HOME = "SET_PAGE_NUMBER_STOCKS_HOME/home";
export const RESET_PAGE_NUMBER_STOCKS_HOME = "RESET_PAGE_NUMBER_STOCKS_HOME/home";
export const SET_COMMENTS_HOME = "SET_COMMENTS/home";
// services
export const SET_SERVICES = "SET_SERVICES/services";
export const SHOW_PAGINATION_SERVICES_LOADER = "SHOW_PAGINATION_SERVICES_LOADER/services";
export const HIDE_PAGINATION_SERVICES_LOADER = "HIDE_PAGINATION_SERVICES_LOADER/services";
export const SET_PAGE_NUMBER_SERVICES = "SET_PAGE_NUMBER_SERVICES/services";
export const RESET_PAGE_NUMBER_SERVICES = "RESET_PAGE_NUMBER_SERVICES/services";
